import { describe, it, expect, vi, beforeEach } from 'vitest'
import { generateLlmsTxt } from './llms-txt'
import fs from 'fs'
import path from 'path'
import type { ResolvedConfig } from '../types'

vi.mock('fs')
vi.mock('path')

describe('generateLlmsTxt', () => {
  const mockFs = fs as any
  const mockPath = path as any

  beforeEach(() => {
    vi.clearAllMocks()
    mockPath.join.mockImplementation((...args: string[]) => args.join('/'))
    mockPath.relative.mockImplementation((from: string, to: string) => 
      to.replace(from + '/', '')
    )
    mockPath.extname.mockImplementation((file: string) => {
      if (file.endsWith('.md')) return '.md'
      if (file.endsWith('.mdx')) return '.mdx'
      return ''
    })
    
    mockFs.readdirSync.mockReturnValue(['README.md', 'guide.md'])
    mockFs.statSync.mockReturnValue({
      isDirectory: () => false,
      isFile: () => true
    })
    mockFs.readFileSync.mockReturnValue('# Test Title\n\nTest content\n\n## Section\n\nMore content')
  })

  const baseConfig: ResolvedConfig = {
    url: 'https://example.com',
    title: 'Test Project',
    description: 'A test project description',
    contentDir: '/project/content',
    outDir: 'public',
    generators: {
      robotsTxt: true,
      llmsTxt: true,
      llmsFullTxt: true,
      rawMarkdown: true,
      manifest: true,
      sitemap: true,
      aiIndex: true,
    }
  }

  it('should generate llms.txt with project title and description', () => {
    const result = generateLlmsTxt(baseConfig)
    
    expect(result).toContain('# Test Project')
    expect(result).toContain('> A test project description')
  })

  it('should include about section', () => {
    const result = generateLlmsTxt(baseConfig)
    
    expect(result).toContain('## About')
    expect(result).toContain('This file provides a structured overview')
    expect(result).toContain('optimized for consumption by Large Language Models')
  })

  it('should include documentation structure', () => {
    const result = generateLlmsTxt(baseConfig)
    
    expect(result).toContain('## Documentation Structure')
  })

  it('should include quick links', () => {
    const result = generateLlmsTxt(baseConfig)
    
    expect(result).toContain('## Quick Links')
    expect(result).toContain('Full Documentation: https://example.com/llms-full.txt')
    expect(result).toContain('Documentation Manifest: https://example.com/docs.json')
    expect(result).toContain('AI-Optimized Index: https://example.com/ai-index.json')
    expect(result).toContain('Sitemap: https://example.com/sitemap.xml')
  })

  it('should include LLM instructions', () => {
    const result = generateLlmsTxt(baseConfig)
    
    expect(result).toContain('## For LLMs')
    expect(result).toContain('To get the complete documentation in a single file')
    expect(result).toContain('https://example.com/llms-full.txt')
    expect(result).toContain('For structured access to individual pages')
    expect(result).toContain('https://example.com/docs.json')
    expect(result).toContain('For RAG (Retrieval Augmented Generation) systems')
    expect(result).toContain('https://example.com/ai-index.json')
  })

  it('should include footer', () => {
    const result = generateLlmsTxt(baseConfig)
    
    expect(result).toContain('Generated by aeo.js')
    expect(result).toContain('Learn more at https://aeojs.org')
  })

  it('should handle missing description', () => {
    const config: ResolvedConfig = {
      ...baseConfig,
      description: undefined as any,
    }
    
    const result = generateLlmsTxt(config)
    
    expect(result).not.toContain('> ')
    expect(result).toContain('# Test Project')
  })

  it('should handle nested directory structure', () => {
    mockFs.readdirSync.mockImplementation((dir: string) => {
      if (dir === '/project/content') return ['docs', 'README.md']
      if (dir.includes('docs')) return ['guide.md', 'api.md']
      return []
    })
    mockFs.statSync.mockImplementation((path: string) => ({
      isDirectory: () => path.includes('docs') && !path.includes('.md'),
      isFile: () => path.includes('.md')
    }))
    
    const result = generateLlmsTxt(baseConfig)
    
    expect(result).toContain('### Main Documentation')
    expect(result).toContain('### docs')
  })

  it('should extract title from markdown content', () => {
    mockFs.readFileSync.mockImplementation((file: string) => {
      if (file.includes('README')) {
        return '---\ntitle: Custom Title\ndescription: Custom desc\n---\n# Content Title\n\nContent'
      }
      return '# Regular Title\n\nContent'
    })
    
    const result = generateLlmsTxt(baseConfig)
    
    expect(result).toContain('[Custom Title]')
  })
})