import { readdirSync, readFileSync, statSync } from 'fs';
import { join, relative, extname } from 'path';
import type { ResolvedConfig } from '../types';
import { parseFrontmatter, bumpHeadings } from './utils';

function collectAndConcatenateMarkdown(dir: string, base: string = dir): string[] {
  const sections: string[] = [];
  
  try {
    const entries = readdirSync(dir).sort();
    
    for (const entry of entries) {
      const fullPath = join(dir, entry);
      const stat = statSync(fullPath);
      
      if (stat.isDirectory() && !entry.startsWith('.') && entry !== 'node_modules') {
        const subSections = collectAndConcatenateMarkdown(fullPath, base);
        if (subSections.length > 0) {
          sections.push(...subSections);
        }
      } else if (stat.isFile() && (extname(entry) === '.md' || extname(entry) === '.mdx')) {
        const content = readFileSync(fullPath, 'utf-8');
        const { frontmatter, content: mainContent } = parseFrontmatter(content);
        const relativePath = relative(base, fullPath);
        
        const sectionLines: string[] = [
          '---',
          '',
          `# ${frontmatter.title || relativePath}`,
          '',
          `Source: ${relativePath}`,
          '',
        ];
        
        if (frontmatter.description) {
          sectionLines.push(`> ${frontmatter.description}`);
          sectionLines.push('');
        }
        
        const bumpedContent = bumpHeadings(mainContent, 1);
        sectionLines.push(bumpedContent);
        sectionLines.push('');
        
        sections.push(sectionLines.join('\n'));
      }
    }
  } catch (error) {
    console.warn(`Warning: Could not read directory ${dir}:`, error);
  }
  
  return sections;
}

export function generateLlmsFullTxt(config: ResolvedConfig): string {
  const lines: string[] = [
    `# ${config.title} - Complete Documentation`,
    '',
    `This file contains all documentation concatenated into a single file for easy consumption by LLMs.`,
    '',
  ];
  
  if (config.description) {
    lines.push(`> ${config.description}`);
    lines.push('');
  }
  
  lines.push('## Table of Contents');
  lines.push('');
  lines.push('This document includes all markdown documentation from this project.');
  lines.push('Each section is separated by a horizontal rule (---) for easy parsing.');
  lines.push('');
  
  const sections = collectAndConcatenateMarkdown(config.contentDir);
  
  if (sections.length > 0) {
    lines.push(...sections);
  } else {
    lines.push('No documentation files found.');
    lines.push('');
  }
  
  lines.push('---');
  lines.push('');
  lines.push('## About This Document');
  lines.push('');
  lines.push('This concatenated documentation file is generated automatically by aeo.js');
  lines.push('to make it easier for AI systems to understand the complete context of this project.');
  lines.push('');
  lines.push(`For a structured index, see: ${config.url}/llms.txt`);
  lines.push(`For individual files, see: ${config.url}/docs.json`);
  lines.push('');
  lines.push('Generated by aeo.js - https://aeojs.org');
  
  return lines.join('\n');
}