import { describe, it, expect } from 'vitest';
import { remoteAuditSite, buildRemoteReport, detectAeoJs, formatRemoteReport } from './remote-audit';
import type { DiscoveryResult, CrawledPage } from './remote-crawl';
import { AI_BOTS } from './remote-crawl';

function makeDiscovery(overrides: Partial<DiscoveryResult> = {}): DiscoveryResult {
  return {
    robotsTxt: { exists: true, content: 'User-agent: *\nDisallow:\n', hasAiDisallow: false },
    llmsTxt: { exists: true, contentLength: 100, content: '# Site\n' },
    llmsFullTxt: { exists: false, contentLength: 0 },
    sitemap: { exists: true, urls: [] },
    aiIndex: { exists: false, content: null },
    homepage: null,
    botAccess: AI_BOTS.map((b) => ({ ...b, allowed: true })),
    ...overrides,
  };
}

const RICH_CONTENT = [
  'This product helps over 10,000 developers optimize their sites for AI answer engines every single month of the year.',
  'The audit covers five categories and produces a score from 0 to 100 based on measurable signals found in the HTML.',
  'What is AEO?\nAnswer Engine Optimization is the practice of making content easy for AI assistants to find and cite.',
].join('\n\n');

function makePage(overrides: Partial<CrawledPage> = {}): CrawledPage {
  const html = `<!doctype html><html><head>
    <title>A Reasonably Sized Page Title</title>
    <meta name="description" content="A description that is comfortably between fifty and two hundred characters long for the meta check.">
    <meta property="og:title" content="A Page">
    <link rel="canonical" href="https://a.com/">
    <script type="application/ld+json">{"@type":"Organization","name":"Acme","logo":"https://a.com/logo.png"}</script>
    <script type="application/ld+json">{"@type":"WebPage","name":"Home"}</script>
    <script type="application/ld+json">{"@type":"FAQPage"}</script>
  </head><body>
    <h1>Heading</h1>
    <ul><li>One</li><li>Two</li></ul>
    <img src="x.png" alt="described image">
    <p>${RICH_CONTENT}</p>
  </body></html>`;
  return {
    url: 'https://a.com/',
    pathname: '/',
    html,
    title: 'A Reasonably Sized Page Title',
    description: 'A description that is comfortably between fifty and two hundred characters long for the meta check.',
    content: RICH_CONTENT,
    jsonLd: [
      { '@type': 'Organization', name: 'Acme', logo: 'https://a.com/logo.png' },
      { '@type': 'WebPage', name: 'Home' },
      { '@type': 'FAQPage' },
    ],
    ogTags: { 'og:title': 'A Page' },
    ...overrides,
  };
}

describe('remoteAuditSite', () => {
  it('scores a well-optimized site high across all categories', () => {
    const result = remoteAuditSite(makeDiscovery(), [makePage()]);
    expect(result.categories).toHaveLength(5);
    for (const cat of result.categories) {
      expect(cat.maxScore).toBe(20);
    }
    expect(result.score).toBeGreaterThanOrEqual(90);
    expect(result.issues.length).toBeLessThanOrEqual(2);
  });

  it('scores an empty site low and reports issues with fixes', () => {
    const discovery = makeDiscovery({
      robotsTxt: { exists: false, content: null, hasAiDisallow: false },
      llmsTxt: { exists: false, contentLength: 0, content: null },
      sitemap: { exists: false, urls: [] },
    });
    const result = remoteAuditSite(discovery, []);
    expect(result.score).toBeLessThan(40);
    expect(result.issues.length).toBeGreaterThan(5);
    expect(result.issues.some((i) => i.fix?.includes('llms.txt'))).toBe(true);
    expect(result.suggestions.length).toBeLessThanOrEqual(5);
  });

  it('penalizes AI Access when major bots are blocked', () => {
    const blockedAccess = AI_BOTS.map((b) => ({
      ...b,
      allowed: !['GPTBot', 'ClaudeBot', 'PerplexityBot'].includes(b.bot),
    }));
    const result = remoteAuditSite(makeDiscovery({ botAccess: blockedAccess }), [makePage()]);
    const aiAccess = result.categories.find((c) => c.name === 'AI Access')!;
    expect(aiAccess.checks.find((c) => c.label.startsWith('Major AI bots'))?.passed).toBe(false);
  });
});

describe('detectAeoJs', () => {
  it('detects via llms.txt signature', () => {
    const discovery = makeDiscovery({
      llmsTxt: { exists: true, contentLength: 50, content: '# Site\n\nGenerated by aeo.js\n' },
    });
    expect(detectAeoJs(discovery, [])).toBe(true);
  });

  it('detects via widget classes in HTML', () => {
    const page = makePage({ html: '<html><body><div class="aeo-toggle"></div></body></html>' });
    expect(detectAeoJs(makeDiscovery(), [page])).toBe(true);
  });

  it('returns false without signatures', () => {
    const page = makePage({ html: '<html><body><p>plain</p></body></html>' });
    expect(detectAeoJs(makeDiscovery(), [page])).toBe(false);
  });
});

describe('buildRemoteReport', () => {
  it('builds a full report with citability and platform hints', () => {
    const report = buildRemoteReport('https://a.com', makeDiscovery(), [makePage()]);

    expect(report.url).toBe('https://a.com');
    expect(report.audit.score).toBeGreaterThan(0);
    expect(report.citability.pages).toHaveLength(1);
    expect(report.citability.averageScore).toBe(report.citability.pages[0].score);

    const platforms = report.platformHints.map((h) => h.platform);
    expect(platforms).toContain('ChatGPT / SearchGPT');
    expect(platforms).toContain('Perplexity');
    expect(platforms).toContain('Claude');
    expect(platforms).toContain('Gemini');
  });

  it('flags Claude as critical when ClaudeBot is blocked', () => {
    const botAccess = AI_BOTS.map((b) => ({ ...b, allowed: b.bot !== 'ClaudeBot' }));
    const report = buildRemoteReport('https://a.com', makeDiscovery({ botAccess }), [makePage()]);
    const claude = report.platformHints.find((h) => h.platform === 'Claude')!;
    expect(claude.status).toBe('critical');
    expect(claude.tips.some((t) => t.includes('Unblock ClaudeBot'))).toBe(true);
  });

  it('handles a site with no crawled pages', () => {
    const report = buildRemoteReport('https://a.com', makeDiscovery(), []);
    expect(report.citability.averageScore).toBe(0);
    expect(report.audit.score).toBeGreaterThanOrEqual(0);
  });
});

describe('formatRemoteReport', () => {
  it('renders score, files, bot access, and categories', () => {
    const report = buildRemoteReport('https://a.com', makeDiscovery(), [makePage()]);
    const text = formatRemoteReport(report);

    expect(text).toContain('GEO Readiness Score for https://a.com');
    expect(text).toContain('+ robots.txt');
    expect(text).toContain('+ llms.txt');
    expect(text).toContain('- llms-full.txt');
    expect(text).toContain('AI crawler access:');
    expect(text).toContain('AI Access:');
    expect(text).toContain('Citability:');
  });

  it('lists blocked bots and the install hint for non-aeo.js sites', () => {
    const botAccess = AI_BOTS.map((b) => ({ ...b, allowed: b.bot !== 'GPTBot' }));
    const page = makePage({ html: '<html><body><p>plain</p></body></html>', jsonLd: [] });
    const report = buildRemoteReport('https://a.com', makeDiscovery({ botAccess }), [page]);
    const text = formatRemoteReport(report);

    expect(text).toContain('Blocked: GPTBot');
    expect(text).toContain('npm install aeo.js');
  });
});
