import type { ResolvedAeoConfig } from '../types';

const AI_CRAWLERS = [
  'GPTBot',
  'OAI-SearchBot',
  'ChatGPT-User',
  'ClaudeBot',
  'Claude-Web',
  'anthropic-ai',
  'PerplexityBot',
  'Google-Extended',
  'Gemini-Deep-Research',
  'Bingbot',
  'FacebookBot',
  'meta-externalagent',
  'Amazonbot',
  'Applebot',
  'DeepSeekBot',
  'Bytespider',
  'cohere-ai',
  'CCBot',
  'DiffBot',
  'YouBot',
  'FirecrawlAgent',
  'Crawl4AI',
  'BraveBot',
  'SemrushBot',
  'AhrefsBot',
  'MJ12bot',
  'DotBot',
  'DataForSeoBot',
  'Screaming Frog SEO Spider',
  'SEOkicks',
  'SEMrushBot',
  'BLEXBot',
  'Yandex',
  'Baiduspider',
  'Sogou',
  'Exabot',
  'facebookexternalhit',
  'LinkedInBot',
  'WhatsApp',
  'Slackbot',
  'TwitterBot',
  'TelegramBot',
  'Discordbot',
  'PinterestBot',
  'TumblrBot',
  'ViberBot',
  'SkypeUriPreview',
  'redditbot',
  'Snapchat',
  'TikTok',
];

export function generateRobotsTxt(config: ResolvedAeoConfig): string {
  const lines: string[] = [
    '# robots.txt generated by aeo.js',
    '# Allow AI crawlers to index this site',
    '',
    '# Traditional search engines',
    'User-agent: Googlebot',
    'Allow: /',
    '',
    'User-agent: Bingbot',
    'Allow: /',
    '',
    '# AI crawlers and answer engines',
  ];
  
  for (const crawler of AI_CRAWLERS) {
    lines.push(`User-agent: ${crawler}`);
    lines.push('Allow: /');
    lines.push('');
  }
  
  lines.push('# Default for all other bots');
  lines.push('User-agent: *');
  lines.push('Allow: /');
  lines.push('');
  
  if (config.url) {
    lines.push(`Sitemap: ${config.url}/sitemap.xml`);
  }
  
  lines.push('');
  lines.push('# AEO (Answer Engine Optimization) files');
  lines.push('# These help LLMs understand your content better');
  lines.push(`# ${config.url}/llms.txt`);
  lines.push(`# ${config.url}/llms-full.txt`);
  lines.push(`# ${config.url}/docs.json`);
  lines.push(`# ${config.url}/ai-index.json`);
  
  return lines.join('\n');
}